# .github/FUNDING.yml
# This file enables the Sponsor button on your GitHub repo.
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

buy_me_a_coffee: exceltographviz   # Replace with your Buy Me a Coffee username (one only)